version: '3.8'

services:
  web:
    build: .
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./db/:/app/db/
      - ./web/:/app/web/
      - ./songlen/:/app/songlen/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
